pragma solidity 0.8.17;

contract AvailEventScaleChunks {
    enum CHUNK_TYPE{ CONSTANT_SIZE, COMPACT, SEQUENCE }

    struct Chunk {
        CHUNK_TYPE chunk_type;
        uint32 size;
        Chunk[] sequence_chunks;
    }

    mapping(uint8 => mapping(uint8 => Chunk[])) event_chunks;

    constructor() {
        event_chunks[0][0].push();
        event_chunks[0][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[0][0][0].size = 14;
        event_chunks[0][1].push();
        event_chunks[0][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[0][1][0].size = 15;
        event_chunks[0][3].push();
        event_chunks[0][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[0][3][0].size = 32;
        event_chunks[0][4].push();
        event_chunks[0][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[0][4][0].size = 32;
        event_chunks[0][5].push();
        event_chunks[0][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[0][5][0].size = 64;
        event_chunks[1][0].push();
        event_chunks[1][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[1][0][0].size = 9;
        event_chunks[1][3].push();
        event_chunks[1][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[1][3][0].size = 6;
        event_chunks[5][0].push();
        event_chunks[5][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[5][0][0].size = 36;
        event_chunks[5][1].push();
        event_chunks[5][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[5][1][0].size = 4;
        event_chunks[5][2].push();
        event_chunks[5][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[5][2][0].size = 36;
        event_chunks[6][0].push();
        event_chunks[6][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][0][0].size = 48;
        event_chunks[6][1].push();
        event_chunks[6][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][1][0].size = 48;
        event_chunks[6][2].push();
        event_chunks[6][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][2][0].size = 80;
        event_chunks[6][3].push();
        event_chunks[6][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][3][0].size = 64;
        event_chunks[6][4].push();
        event_chunks[6][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][4][0].size = 48;
        event_chunks[6][5].push();
        event_chunks[6][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][5][0].size = 48;
        event_chunks[6][6].push();
        event_chunks[6][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][6][0].size = 81;
        event_chunks[6][7].push();
        event_chunks[6][7][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][7][0].size = 48;
        event_chunks[6][8].push();
        event_chunks[6][8][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][8][0].size = 48;
        event_chunks[6][9].push();
        event_chunks[6][9][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[6][9][0].size = 48;
        event_chunks[9][0].push();
        event_chunks[9][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[9][0][0].size = 2;
        event_chunks[9][1].push();
        event_chunks[9][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[9][1][0].size = 2;
        event_chunks[9][2].push();
        event_chunks[9][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[9][2][0].size = 48;
        event_chunks[9][3].push();
        event_chunks[9][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[9][3][0].size = 48;
        event_chunks[9][4].push();
        event_chunks[9][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[9][4][0].size = 4;
        event_chunks[9][5].push();
        event_chunks[9][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[9][5][0].size = 4;
        event_chunks[10][0].push();
        event_chunks[10][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][0][0].size = 36;
        event_chunks[10][1].push();
        event_chunks[10][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][1][0].size = 48;
        event_chunks[10][2].push();
        event_chunks[10][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][2][0].size = 48;
        event_chunks[10][3].push();
        event_chunks[10][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][3][0].size = 4;
        event_chunks[10][5].push();
        event_chunks[10][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][5][0].size = 48;
        event_chunks[10][6].push();
        event_chunks[10][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][6][0].size = 48;
        event_chunks[10][7].push();
        event_chunks[10][7][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][7][0].size = 48;
        event_chunks[10][8].push();
        event_chunks[10][8][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][8][0].size = 64;
        event_chunks[10][10].push();
        event_chunks[10][10][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][10][0].size = 32;
        event_chunks[10][11].push();
        event_chunks[10][11][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[10][11][0].size = 36;
        event_chunks[11][0].push();
        event_chunks[11][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[11][0][0].size = 4;
        event_chunks[12][0].push();
        event_chunks[12][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][0][0].size = 20;
        event_chunks[12][1].push();
        event_chunks[12][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][1][0].size = 20;
        event_chunks[12][1].push();
        event_chunks[12][1][1].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[12][1][1].sequence_chunks.push();
        event_chunks[12][1][1].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][1][1].sequence_chunks[0].size = 32;
        event_chunks[12][3].push();
        event_chunks[12][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][3][0].size = 5;
        event_chunks[12][4].push();
        event_chunks[12][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][4][0].size = 4;
        event_chunks[12][5].push();
        event_chunks[12][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][5][0].size = 4;
        event_chunks[12][6].push();
        event_chunks[12][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][6][0].size = 4;
        event_chunks[12][7].push();
        event_chunks[12][7][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][7][0].size = 10;
        event_chunks[12][8].push();
        event_chunks[12][8][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][8][0].size = 64;
        event_chunks[12][9].push();
        event_chunks[12][9][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][9][0].size = 32;
        event_chunks[12][10].push();
        event_chunks[12][10][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][10][0].size = 68;
        event_chunks[12][11].push();
        event_chunks[12][11][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][11][0].size = 80;
        event_chunks[12][12].push();
        event_chunks[12][12][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][12][0].size = 80;
        event_chunks[12][13].push();
        event_chunks[12][13][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][13][0].size = 36;
        event_chunks[12][14].push();
        event_chunks[12][14][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][14][0].size = 36;
        event_chunks[12][15].push();
        event_chunks[12][15][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][15][0].size = 112;
        event_chunks[12][16].push();
        event_chunks[12][16][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[12][16][0].size = 32;
        event_chunks[13][0].push();
        event_chunks[13][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[13][0][0].size = 72;
        event_chunks[13][1].push();
        event_chunks[13][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[13][1][0].size = 73;
        event_chunks[13][2].push();
        event_chunks[13][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[13][2][0].size = 32;
        event_chunks[13][3].push();
        event_chunks[13][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[13][3][0].size = 32;
        event_chunks[13][4].push();
        event_chunks[13][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[13][4][0].size = 38;
        event_chunks[13][5].push();
        event_chunks[13][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[13][5][0].size = 38;
        event_chunks[13][6].push();
        event_chunks[13][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[13][6][0].size = 40;
        event_chunks[14][0].push();
        event_chunks[14][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[14][0][0].size = 72;
        event_chunks[14][1].push();
        event_chunks[14][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[14][1][0].size = 73;
        event_chunks[14][2].push();
        event_chunks[14][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[14][2][0].size = 32;
        event_chunks[14][3].push();
        event_chunks[14][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[14][3][0].size = 32;
        event_chunks[14][4].push();
        event_chunks[14][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[14][4][0].size = 38;
        event_chunks[14][5].push();
        event_chunks[14][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[14][5][0].size = 38;
        event_chunks[14][6].push();
        event_chunks[14][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[14][6][0].size = 40;
        event_chunks[15][0].push();
        event_chunks[15][0][0].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[15][0][0].sequence_chunks.push();
        event_chunks[15][0][0].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[15][0][0].sequence_chunks[0].size = 48;
        event_chunks[15][3].push();
        event_chunks[15][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[15][3][0].size = 32;
        event_chunks[15][4].push();
        event_chunks[15][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[15][4][0].size = 32;
        event_chunks[15][5].push();
        event_chunks[15][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[15][5][0].size = 48;
        event_chunks[15][6].push();
        event_chunks[15][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[15][6][0].size = 48;
        event_chunks[17][0].push();
        event_chunks[17][0][0].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[17][0][0].sequence_chunks.push();
        event_chunks[17][0][0].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[17][0][0].sequence_chunks[0].size = 40;
        event_chunks[18][0].push();
        event_chunks[18][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[18][0][0].size = 4;
        event_chunks[18][1].push();
        event_chunks[18][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[18][1][0].size = 16;
        event_chunks[18][2].push();
        event_chunks[18][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[18][2][0].size = 52;
        event_chunks[18][3].push();
        event_chunks[18][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[18][3][0].size = 20;
        event_chunks[18][4].push();
        event_chunks[18][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[18][4][0].size = 16;
        event_chunks[18][5].push();
        event_chunks[18][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[18][5][0].size = 16;
        event_chunks[18][6].push();
        event_chunks[18][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[18][6][0].size = 16;
        event_chunks[19][0].push();
        event_chunks[19][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[19][0][0].size = 6;
        event_chunks[19][1].push();
        event_chunks[19][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[19][1][0].size = 32;
        event_chunks[19][2].push();
        event_chunks[19][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[19][2][0].size = 6;
        event_chunks[20][0].push();
        event_chunks[20][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[20][0][0].size = 32;
        event_chunks[20][2].push();
        event_chunks[20][2][0].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[20][2][0].sequence_chunks.push();
        event_chunks[20][2][0].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[20][2][0].sequence_chunks[0].size = 32;
        event_chunks[20][2][0].sequence_chunks.push();
        event_chunks[20][2][0].sequence_chunks[1].chunk_type = CHUNK_TYPE.COMPACT;
        event_chunks[20][2][0].sequence_chunks.push();
        event_chunks[20][2][0].sequence_chunks[2].chunk_type = CHUNK_TYPE.COMPACT;
        event_chunks[20][2][0].sequence_chunks.push();
        event_chunks[20][2][0].sequence_chunks[3].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[20][2][0].sequence_chunks[3].sequence_chunks.push();
        event_chunks[20][2][0].sequence_chunks[3].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[20][2][0].sequence_chunks[3].sequence_chunks[0].size = 32;
        event_chunks[20][2][0].sequence_chunks[3].sequence_chunks.push();
        event_chunks[20][2][0].sequence_chunks[3].sequence_chunks[1].chunk_type = CHUNK_TYPE.COMPACT;
        event_chunks[22][0].push();
        event_chunks[22][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[22][0][0].size = 16;
        event_chunks[22][0].push();
        event_chunks[22][0][1].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[22][0][1].sequence_chunks.push();
        event_chunks[22][0][1].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[22][0][1].sequence_chunks[0].size = 1;
        event_chunks[24][0].push();
        event_chunks[24][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[24][0][0].size = 8;
        event_chunks[24][1].push();
        event_chunks[24][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[24][1][0].size = 8;
        event_chunks[24][2].push();
        event_chunks[24][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[24][2][0].size = 9;
        event_chunks[24][2].push();
        event_chunks[24][2][1].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[24][2][1].sequence_chunks.push();
        event_chunks[24][2][1].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[24][2][1].sequence_chunks[0].size = 1;
        event_chunks[24][2].push();
        event_chunks[24][2][2].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[24][2][2].size = 6;
        event_chunks[25][0].push();
        event_chunks[25][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[25][0][0].size = 4;
        event_chunks[25][1].push();
        event_chunks[25][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[25][1][0].size = 20;
        event_chunks[25][2].push();
        event_chunks[25][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[25][2][0].size = 4;
        event_chunks[25][3].push();
        event_chunks[25][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[25][3][0].size = 36;
        event_chunks[25][4].push();
        event_chunks[25][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[25][4][0].size = 52;
        event_chunks[25][5].push();
        event_chunks[25][5][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[25][5][0].size = 4;
        event_chunks[25][6].push();
        event_chunks[25][6][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[25][6][0].size = 4;
        event_chunks[26][0].push();
        event_chunks[26][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[26][0][0].size = 32;
        event_chunks[26][1].push();
        event_chunks[26][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[26][1][0].size = 32;
        event_chunks[26][2].push();
        event_chunks[26][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[26][2][0].size = 80;
        event_chunks[26][3].push();
        event_chunks[26][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[26][3][0].size = 32;
        event_chunks[26][4].push();
        event_chunks[26][4][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[26][4][0].size = 80;
        event_chunks[28][0].push();
        event_chunks[28][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[28][0][0].size = 48;
        event_chunks[29][0].push();
        event_chunks[29][0][0].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[29][0][0].sequence_chunks.push();
        event_chunks[29][0][0].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[29][0][0].sequence_chunks[0].size = 1;
        event_chunks[29][0].push();
        event_chunks[29][0][1].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[29][0][1].size = 32;
        event_chunks[29][0].push();
        event_chunks[29][0][2].chunk_type = CHUNK_TYPE.COMPACT;
        event_chunks[29][1].push();
        event_chunks[29][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[29][1][0].size = 32;
        event_chunks[29][1].push();
        event_chunks[29][1][1].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[29][1][1].sequence_chunks.push();
        event_chunks[29][1][1].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[29][1][1].sequence_chunks[0].size = 1;
        event_chunks[29][2].push();
        event_chunks[29][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[29][2][0].size = 8;
        event_chunks[30][0].push();
        event_chunks[30][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[30][0][0].size = 40;
        event_chunks[30][1].push();
        event_chunks[30][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[30][1][0].size = 32;
        event_chunks[31][0].push();
        event_chunks[31][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[31][0][0].size = 76;
        event_chunks[31][0].push();
        event_chunks[31][0][1].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[31][0][1].sequence_chunks.push();
        event_chunks[31][0][1].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[31][0][1].sequence_chunks[0].size = 1;
        event_chunks[31][1].push();
        event_chunks[31][1][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[31][1][0].size = 68;
        event_chunks[31][1].push();
        event_chunks[31][1][1].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[31][1][1].sequence_chunks.push();
        event_chunks[31][1][1].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[31][1][1].sequence_chunks[0].size = 1;
        event_chunks[31][2].push();
        event_chunks[31][2][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[31][2][0].size = 64;
        event_chunks[31][2].push();
        event_chunks[31][2][1].chunk_type = CHUNK_TYPE.SEQUENCE;
        event_chunks[31][2][1].sequence_chunks.push();
        event_chunks[31][2][1].sequence_chunks[0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[31][2][1].sequence_chunks[0].size = 1;
        event_chunks[31][3].push();
        event_chunks[31][3][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[31][3][0].size = 52;
        event_chunks[32][0].push();
        event_chunks[32][0][0].chunk_type = CHUNK_TYPE.CONSTANT_SIZE;
        event_chunks[32][0][0].size = 72;
    }
}
